server:
  port: 8127
  servlet:
    context-path: /
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Wilton-File
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
  jackson:
    generator:
      write_numbers_as_strings: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 文件大小限制
  servlet:
    multipart:
      enabled: true
      max-request-size: 1024MB
      max-file-size: 1024MB
  mail:
    host: smtp.exmail.qq.com #发送邮件服务器
    username: no-reply@vihacker.top #邮箱
    password: DY***********pxDm #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: ViHacker #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: no-reply@vihacker.top #与上面的username保持一致
    from-name: ViHacker
wilton:
  security:
    ignored:
      urls: #安全路径白名单
        - /favicon.ico
        - /static/assets/**/**
        - /assets/**
        - /assets/**/**
        - /assets/**/**/**
        - /wechat/**
  redisKey: vihacker.


mybatis-plus:
  type-aliases-package: cn.wilton.framework.file*.entity
  type-enums-package: cn.wilton.framework.file.common.entity.enums
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      # 删除状态为1
      logic-delete-value: 1
      # 没有删除状态为0
      logic-not-delete-value: 0
    banner: false
    configuration:
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
      map-underscore-to-camel-case: true
      # 返回map时true:当查询数据为空时字段返回为null,false:不加这个查询数据为空时，字段将被隐藏
      call-setters-on-nulls: true

logging:
  config: classpath:logback-spring.xml

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true
vihacker:
  redis:
    enable: true